// AUTO-GENERATED BY build.js - DO NOT EDIT DIRECTLY
window.APP_CONFIG = {
  "VITE_CLERK_PUBLISHABLE_KEY": "pk_test_cG9zc2libGUtdHJvdXQtNTkuY2xlcmsuYWNjb3VudHMuZGV2JA",
  "VITE_UPI_ID": "vinay.makvana@ptyes",
  "VITE_UPI_NAME": "Vinay Kumar Makvana"
};
